# Generated by Django 4.1.7 on 2023-03-02 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_topping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='text',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='date_added',
        ),
    ]
